
export const ADD = 'ADD';
export const SUBTRACT = 'SUBTRACT';

export const HANDLER_ADD = 'HANDLER_ADD';
export const HANDLER_REMOVE = 'HANDLER_REMOVE';
export const HANDLER_ACTIVATE = 'HANDLER_ACTIVATE';
export const HANDLER_DEACTIVATE = 'HANDLER_DEACTIVATE';

export const RECEIVER_ADD = 'RECEIVER_ADD';
export const RECEIVER_REMOVE = 'RECEIVER_REMOVE';
export const RECEIVER_ACTIVATE = 'RECEIVER_ACTIVATE';
export const RECEIVER_DEACTIVATE = 'RECEIVER_DEACTIVATE';
