
export const ADD = 'ADD';
export const SUBTRACT = 'SUBTRACT';
export const START_APP = 'START_APP';
export const DEV_MODE = 'DEV_MODE';

export const ADD_PLUGIN = 'ADD_PLUGIN';
export const SET_PLUGIN_VALUE = 'SET_PLUGIN_VALUE';

export const SENDER_ACTIVATE = 'SENDER_ACTIVATE';
export const SENDER_DEACTIVATE = 'SENDER_DEACTIVATE';

export const RECEIVER_ACTIVATE = 'RECEIVER_ACTIVATE';
export const RECEIVER_DEACTIVATE = 'RECEIVER_DEACTIVATE';

